name: data-analysis-env
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - jupyterlab
  - ipykernel
  - xarray
  - plotly
  - geopandas
  - s3fs
  - fsspec
  - numpy
  - pandas
  - matplotlib
  - h5netcdf
  - cartopy
  - pyproj
  - shapely
  - scipy
  - intake
  - netcdf4
  - cftime
  - gcsfs
